trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: terraform-backend-kv
- group: lib-quackers-bank
- name: TF_VAR_key
  value: $(Build.Repository.Name).tfstate

stages:
  - stage: docker
    jobs:
    - job: docker_stuff
      steps:
      - task: Docker@2
        displayName: Login to ACR
        inputs:
          command: login
          containerRegistry: acrquackbank
      - task: Docker@2
        displayName: Build and Push Function
        inputs:
          buildContext: ./aksfunc
          Dockerfile: ./aksfunc/Dockerfile
          command: buildAndPush
          repository: aksfunc
          containerRegistry: acrquackbank
          tags: |
            latest
            $(Build.BuildNumber)